"""Secret detection and redaction for diagnostic output."""

from __future__ import annotations

import re
from collections.abc import Iterator
from contextlib import contextmanager
from contextvars import ContextVar
from dataclasses import dataclass, field
from typing import Iterable


_BEARER = re.compile(r"Bearer\s+[A-Za-z0-9._~+/=-]+", re.IGNORECASE)
_SECRET_KEYS = {"authorization", "api_key", "apikey", "password", "token"}
_DEFAULT_REDACTED = "[REDACTED]"
_DEFAULT_KEY = "[REDACTED-KEY:{position}]"
_KEY_TOKEN = re.compile(
    r"\[REDACTED-KEY:[1-9][0-9]*\](?:#(?:[2-9]|[1-9][0-9]+))?\Z"
)


class _ProtectedText(str):
    """A JSON-compatible string carrying ranges generated by redaction."""

    def __new__(
        cls, value: str, protected_ranges: tuple[tuple[int, int], ...]
    ) -> _ProtectedText:
        instance = super().__new__(cls, value)
        instance.protected_ranges = protected_ranges
        return instance

    def __reduce__(self) -> tuple[object, tuple[str, tuple[tuple[int, int], ...]]]:
        return type(self), (str(self), self.protected_ranges)


@dataclass(frozen=True, slots=True)
class SecretRedactor:
    """Data model representing the secret redactor."""
    values: tuple[str, ...] = field(repr=False)

    @classmethod
    def with_values(cls, values: Iterable[str]) -> SecretRedactor:
        """Handle the with values operation."""
        unique_values = {value for value in values if value}
        return cls(tuple(sorted(unique_values, key=len, reverse=True)))

    def redact_text(self, value: str) -> str:
        """Handle the redact text operation."""
        safe_unit = _safe_unit(self.values)
        marker = (
            _DEFAULT_REDACTED
            if _safe_generated(_DEFAULT_REDACTED, self.values)
            else safe_unit
        )
        fragments = _protected_fragments(
            value,
            values=self.values,
            marker=marker,
            safe_unit=safe_unit,
        )
        fragments = _replace_regex(fragments, _BEARER, marker)
        for secret in self.values:
            fragments = _replace_literal(fragments, secret, marker)
        return _join_fragments(fragments)

    def redact_data(self, value: object) -> object:
        """Handle the redact data operation."""
        if isinstance(value, str):
            return self.redact_text(value)
        if isinstance(value, list):
            return [self.redact_data(item) for item in value]
        if isinstance(value, tuple):
            return tuple(self.redact_data(item) for item in value)
        if isinstance(value, dict):
            return self._redact_mapping(value)
        return value

    def _redact_mapping(self, value: dict[object, object]) -> dict[object, object]:
        entries: list[tuple[int, object, object, bool]] = []
        reserved: set[object] = set()
        for position, (key, item) in enumerate(value.items(), 1):
            redacted_key = self.redact_text(key) if isinstance(key, str) else key
            changed = redacted_key != key
            entries.append((position, key, item, changed))
            if not changed:
                reserved.add(key)

        result: dict[object, object] = {}
        occupied = set(reserved)
        marker = self._marker()
        safe_unit = _safe_unit(self.values)
        for position, original_key, item, changed in entries:
            output_key = original_key
            if changed:
                standard = _DEFAULT_KEY.format(position=position)
                candidate = (
                    standard
                    if _safe_generated(standard, self.values)
                    else safe_unit * position
                )
                output_key = _available_redacted_key(
                    candidate,
                    occupied,
                    values=self.values,
                    fallback=safe_unit,
                )
                output_key = _protect_all(output_key)
                occupied.add(output_key)
            output_value = (
                _protect_all(marker)
                if str(original_key).casefold() in _SECRET_KEYS
                else self.redact_data(item)
            )
            result[output_key] = output_value
        return result

    def _marker(self) -> str:
        if _safe_generated(_DEFAULT_REDACTED, self.values):
            return _DEFAULT_REDACTED
        return _safe_unit(self.values)


_EMPTY_REDACTOR = SecretRedactor.with_values(())
_CURRENT_REDACTOR: ContextVar[SecretRedactor] = ContextVar(
    "litecoder_secret_redactor", default=_EMPTY_REDACTOR
)


def current_secret_redactor() -> SecretRedactor:
    """Handle the current secret redactor operation."""
    return _CURRENT_REDACTOR.get()


@contextmanager
def bind_secret_redactor(redactor: SecretRedactor) -> Iterator[SecretRedactor]:
    """Handle the bind secret redactor operation."""
    if not isinstance(redactor, SecretRedactor):
        raise TypeError("redactor must be a SecretRedactor")
    token = _CURRENT_REDACTOR.set(redactor)
    try:
        yield redactor
    finally:
        _CURRENT_REDACTOR.reset(token)


def _safe_generated(candidate: str, values: tuple[str, ...]) -> bool:
    return all(secret not in candidate for secret in values)


def _safe_unit(values: tuple[str, ...]) -> str:
    used = set().union(*(set(value) for value in values)) if values else set()
    ranges = (
        (0xE000, 0xF900),
        (0xF0000, 0xFFFFE),
        (0x100000, 0x10FFFE),
    )
    for start, stop in ranges:
        for codepoint in range(start, stop):
            candidate = chr(codepoint)
            if candidate not in used:
                return candidate
    raise ValueError("configured secrets exhaust redaction marker space")


def _protected_fragments(
    value: str,
    *,
    values: tuple[str, ...],
    marker: str,
    safe_unit: str,
) -> list[tuple[str, bool]]:
    if not isinstance(value, _ProtectedText):
        return [(str(value), False)]
    ranges = _validated_protected_ranges(
        value,
        values=values,
        marker=marker,
        safe_unit=safe_unit,
    )
    if ranges is None:
        return [(str(value), False)]
    fragments: list[tuple[str, bool]] = []
    source = str(value)
    cursor = 0
    for start, end in ranges:
        if cursor < start:
            fragments.append((source[cursor:start], False))
        if start < end:
            fragments.append((source[start:end], True))
        cursor = end
    if cursor < len(source):
        fragments.append((source[cursor:], False))
    return fragments


def _validated_protected_ranges(
    value: _ProtectedText,
    *,
    values: tuple[str, ...],
    marker: str,
    safe_unit: str,
) -> tuple[tuple[int, int], ...] | None:
    ranges = getattr(value, "protected_ranges", None)
    if not isinstance(ranges, tuple) or not ranges:
        return None
    source = str(value)
    previous_end = 0
    validated: list[tuple[int, int]] = []
    for item in ranges:
        if not isinstance(item, tuple) or len(item) != 2:
            return None
        start, end = item
        if (
            isinstance(start, bool)
            or isinstance(end, bool)
            or not isinstance(start, int)
            or not isinstance(end, int)
            or start < previous_end
            or start < 0
            or end <= start
            or end > len(source)
        ):
            return None
        token = source[start:end]
        if not _is_current_redacted_token(
            token,
            values=values,
            marker=marker,
            safe_unit=safe_unit,
        ):
            return None
        validated.append((start, end))
        previous_end = end
    return tuple(validated)


def _is_current_redacted_token(
    token: str,
    *,
    values: tuple[str, ...],
    marker: str,
    safe_unit: str,
) -> bool:
    if not _safe_generated(token, values) or _BEARER.search(token) is not None:
        return False
    if token == marker or (token and not token.strip(safe_unit)):
        return True
    if _KEY_TOKEN.fullmatch(token) is not None:
        return True
    base = token.rstrip(safe_unit)
    return base != token and _KEY_TOKEN.fullmatch(base) is not None


def _replace_regex(
    fragments: list[tuple[str, bool]], pattern: re.Pattern[str], marker: str
) -> list[tuple[str, bool]]:
    result: list[tuple[str, bool]] = []
    for text, protected in fragments:
        if protected:
            result.append((text, True))
            continue
        cursor = 0
        for match in pattern.finditer(text):
            if cursor < match.start():
                result.append((text[cursor : match.start()], False))
            result.append((marker, True))
            cursor = match.end()
        if cursor < len(text):
            result.append((text[cursor:], False))
    return result


def _replace_literal(
    fragments: list[tuple[str, bool]], secret: str, marker: str
) -> list[tuple[str, bool]]:
    result: list[tuple[str, bool]] = []
    for text, protected in fragments:
        if protected:
            result.append((text, True))
            continue
        cursor = 0
        while True:
            found = text.find(secret, cursor)
            if found < 0:
                if cursor < len(text):
                    result.append((text[cursor:], False))
                break
            if cursor < found:
                result.append((text[cursor:found], False))
            result.append((marker, True))
            cursor = found + len(secret)
    return result


def _join_fragments(fragments: list[tuple[str, bool]]) -> str:
    merged: list[tuple[str, bool]] = []
    for text, protected in fragments:
        if not text:
            continue
        if merged and merged[-1][1] is protected:
            previous, _ = merged[-1]
            merged[-1] = (previous + text, protected)
        else:
            merged.append((text, protected))
    if not merged:
        return ""
    rendered = "".join(text for text, _ in merged)
    ranges: list[tuple[int, int]] = []
    cursor = 0
    for text, protected in merged:
        end = cursor + len(text)
        if protected:
            ranges.append((cursor, end))
        cursor = end
    if not ranges:
        return rendered
    return _ProtectedText(rendered, tuple(ranges))


def _protect_all(value: str) -> _ProtectedText:
    return _ProtectedText(value, ((0, len(value)),))


def _available_redacted_key(
    candidate: str,
    occupied: set[object],
    *,
    values: tuple[str, ...],
    fallback: str,
) -> str:
    if candidate not in occupied:
        return candidate
    suffix = 2
    for _ in range(len(occupied) + 2):
        numbered = f"{candidate}#{suffix}"
        if _safe_generated(numbered, values) and numbered not in occupied:
            return numbered
        suffix += 1
    result = candidate + fallback
    while result in occupied:
        result += fallback
    return result
